
volumes:
  db-data:

networks:
  greenlight-sso-network:
    external: true

services:
  db:
    image: postgres:15-alpine
    container_name: greenlight_db
    env_file:
      - .env.postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: greenlight_web
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default
      - greenlight-sso-network