// Code generated by mockery v2.44.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MailProvider is an autogenerated mock type for the MailProvider type
type MailProvider struct {
	mock.Mock
}

// Send provides a mock function with given fields: recipient, tmplName, tmplData
func (_m *MailProvider) Send(recipient string, tmplName string, tmplData interface{}) error {
	ret := _m.Called(recipient, tmplName, tmplData)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, interface{}) error); ok {
		r0 = rf(recipient, tmplName, tmplData)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMailProvider creates a new instance of MailProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMailProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MailProvider {
	mock := &MailProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
