debug: true
app_secret: d914b337e3c6f088610690c66d3128cfe2dea520018efe4a49b31e6ac552f3b5
app_id: 1
server:
  host: localhost
  port: 8000
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 120s
  shutdown_timeout: 3s
smtp_server:
  host: sandbox.smtp.mailtrap.io
  port: 2525
  timeout: 5s
  sender: Greenlight <no-reply@greenlight.com>
  retries_count: 3
db:
  dsn: "postgres://std_user:1234@localhost:5454/greenlight?sslmode=disable"
  max_conns: 10
  max_conn_idle_time: 5m

limit:
  enabled: true
clients:
  sso:
    addr: "localhost:8080"
    retry_timeout: 2s
    retries_count: 3